import SwiftUI

struct CurriculumBrowserScreen: View {
    @ObservedObject var viewModel: GradeDraftViewModel
    var assignmentID: UUID

    private var results: [CurriculumItem] {
        Array(viewModel.curriculumSearchResults.prefix(viewModel.curriculumResultLimit))
    }

    private var mappedIDs: Set<String> {
        Set(viewModel.assignment(for: assignmentID)?.curriculumMappings.map(\.curriculumItemID) ?? [])
    }

    var body: some View {
        List {
            Section {
                Text(viewModel.curriculumCatalogSummary)
                    .font(.subheadline)
                Text(viewModel.curriculumCatalog.nonEndorsementWarning.isEmpty ? CurriculumCatalogService.sourceWarning : viewModel.curriculumCatalog.nonEndorsementWarning)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
                if !viewModel.curriculumCatalog.icipWarning.isEmpty {
                    Text(viewModel.curriculumCatalog.icipWarning)
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }
                LabeledContent("Catalog version", value: viewModel.curriculumCatalog.sourceVersion)
                LabeledContent("Generated by", value: viewModel.curriculumCatalog.generatedBy)
            } header: {
                Text("Bundled Australian Curriculum")
            } footer: {
                Text("Official entries are read-only reference records. They enter grading packets only after the teacher maps them to this assignment.")
            }

            Section("Filters") {
                TextField("Search code, title, description", text: $viewModel.curriculumSearchText)
                    .textInputAutocapitalization(.never)
                    .accessibilityLabel("Search Australian Curriculum catalog")
                Picker("Kind", selection: $viewModel.curriculumCatalogKindFilter) {
                    Text("Any").tag("")
                    ForEach(viewModel.curriculumAvailableCatalogKinds, id: \.self) { value in
                        Text(value).tag(value)
                    }
                }
                Picker("Learning area", selection: $viewModel.curriculumLearningAreaFilter) {
                    Text("Any").tag("")
                    ForEach(viewModel.curriculumAvailableLearningAreas, id: \.self) { value in
                        Text(value).tag(value)
                    }
                }
                Picker("Subject", selection: $viewModel.curriculumSubjectFilter) {
                    Text("Any").tag("")
                    ForEach(viewModel.curriculumAvailableSubjects, id: \.self) { value in
                        Text(value).tag(value)
                    }
                }
                Picker("Year or band", selection: $viewModel.curriculumYearLevelFilter) {
                    Text("Any").tag("")
                    ForEach(viewModel.curriculumAvailableYearLevelsAndBands, id: \.self) { value in
                        Text(value).tag(value)
                    }
                }
                Button {
                    viewModel.clearCurriculumFilters()
                } label: {
                    Label("Clear filters", systemImage: "line.3.horizontal.decrease.circle")
                }
                .accessibilityLabel("Clear Australian Curriculum filters")
            }

            Section("Mapped to this assignment") {
                let mappedItems = viewModel.mappedCurriculumItemsForCurrentAssignment
                if mappedItems.isEmpty {
                    ContentUnavailableView(
                        "No mapped curriculum references",
                        systemImage: "link.slash",
                        description: Text("Search the bundled catalog and choose Map to include a teacher-selected reference in grading context.")
                    )
                } else {
                    ForEach(mappedItems) { item in
                        CurriculumCatalogRow(item: item, isMapped: true) {
                            viewModel.selectAssignment(assignmentID)
                            viewModel.unmapCurriculumItemFromCurrentAssignment(item)
                        }
                    }
                }
            }

            Section {
                if results.isEmpty {
                    ContentUnavailableView(
                        "No catalog matches",
                        systemImage: "magnifyingglass",
                        description: Text("Adjust the search or filters. Manual teacher-provided curriculum import remains available from the rubric screen.")
                    )
                } else {
                    ForEach(results) { item in
                        CurriculumCatalogRow(item: item, isMapped: mappedIDs.contains(item.id)) {
                            viewModel.selectAssignment(assignmentID)
                            if mappedIDs.contains(item.id) {
                                viewModel.unmapCurriculumItemFromCurrentAssignment(item)
                            } else {
                                viewModel.mapCurriculumItemToCurrentAssignment(item)
                            }
                        }
                    }
                    if viewModel.curriculumSearchResults.count > viewModel.curriculumResultLimit {
                        Button {
                            viewModel.loadMoreCurriculumResults()
                        } label: {
                            Label("Show more results", systemImage: "chevron.down.circle")
                        }
                    }
                }
            } header: {
                Text("Catalog results")
            } footer: {
                Text("AI is not allowed to add curriculum codes or infer official alignment. Only mapped references are used.")
            }
        }
        .navigationTitle("Curriculum Catalog")
        .navigationBarTitleDisplayMode(.inline)
    }
}

private struct CurriculumCatalogRow: View {
    var item: CurriculumItem
    var isMapped: Bool
    var action: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .firstTextBaseline) {
                VStack(alignment: .leading, spacing: 4) {
                    Text(item.code.isEmpty ? item.title : item.code)
                        .font(.headline)
                    Text(item.title)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                Text(isMapped ? "Mapped" : "Available")
                    .font(.caption)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(.thinMaterial, in: Capsule())
            }
            Text(item.shortDescription)
                .font(.footnote)
                .foregroundStyle(.secondary)
            Text("\(item.learningArea) • \(item.subject) • \(item.yearLevel.isEmpty ? item.band : item.yearLevel)")
                .font(.caption)
                .foregroundStyle(.secondary)
            DisclosureGroup("Provenance") {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Source: \(item.sourceName)")
                    Text("Version: \(item.sourceVersion)")
                    Text("URI: \(item.externalURI)")
                    if !item.licenseName.isEmpty { Text("License: \(item.licenseName)") }
                    if !item.sourceAttribution.isEmpty { Text(item.sourceAttribution) }
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            }
            Button(action: action) {
                Label(isMapped ? "Unmap" : "Map", systemImage: isMapped ? "link.slash" : "link")
            }
            .accessibilityLabel(isMapped ? "Unmap curriculum reference \(item.code)" : "Map curriculum reference \(item.code)")
        }
        .padding(.vertical, 6)
    }
}
