import SwiftUI

struct CurriculumBrowserScreen: View {
    @ObservedObject var viewModel: GradeDraftViewModel
    var assignmentID: UUID

    private var results: [CurriculumItem] {
        Array(viewModel.curriculumSearchResults.prefix(viewModel.curriculumResultLimit))
    }

    private var mappedIDs: Set<String> {
        Set(viewModel.assignment(for: assignmentID)?.curriculumMappings.map(\.curriculumItemID) ?? [])
    }

    var body: some View {
        List {
            Section {
                RubricStationeryPage(
                    title: "Curriculum Catalog",
                    subtitle: "Bundled read-only references that teachers can explicitly map into the local grading packet.",
                    tapeLabel: "Catalog",
                    annotation: "MarkForMe does not infer official alignment.",
                    status: .teacherOnly
                ) {
            RubricStationeryCard(
                title: "Bundled Australian Curriculum",
                tapeLabel: "Read-only",
                annotation: "Official entries enter grading packets only after the teacher maps them to this assignment.",
                status: .teacherOnly,
                showsPaperclip: true
            ) {
                VStack(alignment: .leading, spacing: 12) {
                    Text(viewModel.curriculumCatalogSummary)
                        .font(.subheadline)
                    RubricHandwrittenNote(
                        viewModel.curriculumCatalog.nonEndorsementWarning.isEmpty ? CurriculumCatalogService.sourceWarning : viewModel.curriculumCatalog.nonEndorsementWarning,
                        status: .teacherOnly
                    )
                    if !viewModel.curriculumCatalog.icipWarning.isEmpty {
                        RubricHandwrittenNote(viewModel.curriculumCatalog.icipWarning, status: .teacherOnly)
                    }
                    LabeledContent("Catalog version", value: viewModel.curriculumCatalog.sourceVersion)
                    LabeledContent("Generated by", value: viewModel.curriculumCatalog.generatedBy)
                }
            }

            RubricStationeryCard(title: "Filters", tapeLabel: "Search") {
                VStack(alignment: .leading, spacing: 12) {
                    RubricFieldRow(title: "Search") {
                        TextField("Search code, title, description", text: $viewModel.curriculumSearchText)
                            .textInputAutocapitalization(.never)
                            .accessibilityLabel("Search Australian Curriculum catalog")
                    }
                    RubricFieldRow(title: "Kind") {
                        Picker("Kind", selection: $viewModel.curriculumCatalogKindFilter) {
                            Text("Any").tag("")
                            ForEach(viewModel.curriculumAvailableCatalogKinds, id: \.self) { value in
                                Text(value).tag(value)
                            }
                        }
                        .pickerStyle(.menu)
                    }
                    RubricFieldRow(title: "Learning area") {
                        Picker("Learning area", selection: $viewModel.curriculumLearningAreaFilter) {
                            Text("Any").tag("")
                            ForEach(viewModel.curriculumAvailableLearningAreas, id: \.self) { value in
                                Text(value).tag(value)
                            }
                        }
                        .pickerStyle(.menu)
                    }
                    RubricFieldRow(title: "Subject") {
                        Picker("Subject", selection: $viewModel.curriculumSubjectFilter) {
                            Text("Any").tag("")
                            ForEach(viewModel.curriculumAvailableSubjects, id: \.self) { value in
                                Text(value).tag(value)
                            }
                        }
                        .pickerStyle(.menu)
                    }
                    RubricFieldRow(title: "Year or band") {
                        Picker("Year or band", selection: $viewModel.curriculumYearLevelFilter) {
                            Text("Any").tag("")
                            ForEach(viewModel.curriculumAvailableYearLevelsAndBands, id: \.self) { value in
                                Text(value).tag(value)
                            }
                        }
                        .pickerStyle(.menu)
                    }
                    Button {
                        viewModel.clearCurriculumFilters()
                    } label: {
                        Label("Clear filters", systemImage: "line.3.horizontal.decrease.circle")
                            .frame(minHeight: GradeDraftLayout.minimumTapTarget)
                    }
                    .buttonStyle(.bordered)
                    .accessibilityLabel("Clear Australian Curriculum filters")
                }
            }

            RubricStationeryCard(title: "Mapped to this assignment", tapeLabel: "Mapped", status: mappedIDs.isEmpty ? .notStarted : .onTrack) {
                let mappedItems = viewModel.mappedCurriculumItemsForCurrentAssignment
                if mappedItems.isEmpty {
                    ContentUnavailableView(
                        "No mapped curriculum references",
                        systemImage: "link.slash",
                        description: Text("Search the bundled catalog and choose Map to include a teacher-selected reference in grading context.")
                    )
                } else {
                    ForEach(mappedItems) { item in
                        CurriculumCatalogRow(item: item, isMapped: true) {
                            viewModel.selectAssignment(assignmentID)
                            viewModel.unmapCurriculumItemFromCurrentAssignment(item)
                        }
                    }
                }
            }

                RubricStationeryCard(
                    title: "Catalog results",
                    tapeLabel: "Results",
                    annotation: "AI is not allowed to add curriculum codes or infer official alignment. Only mapped references are used.",
                    status: .teacherOnly
                ) {
                    if results.isEmpty {
                        ContentUnavailableView(
                            "No catalog matches",
                            systemImage: "magnifyingglass",
                            description: Text("Adjust the search or filters. Manual teacher-provided curriculum import remains available from the rubric screen.")
                        )
                    } else {
                        ForEach(results) { item in
                            CurriculumCatalogRow(item: item, isMapped: mappedIDs.contains(item.id)) {
                                viewModel.selectAssignment(assignmentID)
                                if mappedIDs.contains(item.id) {
                                    viewModel.unmapCurriculumItemFromCurrentAssignment(item)
                                } else {
                                    viewModel.mapCurriculumItemToCurrentAssignment(item)
                                }
                            }
                        }
                        if viewModel.curriculumSearchResults.count > viewModel.curriculumResultLimit {
                            Button {
                                viewModel.loadMoreCurriculumResults()
                            } label: {
                                Label("Show more results", systemImage: "chevron.down.circle")
                                    .frame(minHeight: GradeDraftLayout.minimumTapTarget)
                            }
                            .buttonStyle(.bordered)
                        }
                    }
                }
            }
            .listRowInsets(EdgeInsets(top: 10, leading: 16, bottom: 10, trailing: 16))
            .listRowBackground(Color.clear)
            .listRowSeparator(.hidden)
            }
        }
        .gradeDraftNativeGroupedList()
        .navigationTitle("Curriculum Catalog")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .tabBar)
        .onAppear { viewModel.selectAssignment(assignmentID) }
    }
}

private struct CurriculumCatalogRow: View {
    var item: CurriculumItem
    var isMapped: Bool
    var action: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .top, spacing: 12) {
                RubricIconBubble(isMapped ? .onTrack : .notStarted)
                    .frame(width: 34, height: 34)
                VStack(alignment: .leading, spacing: 4) {
                    Text(item.code.isEmpty ? item.title : item.code)
                        .font(.system(.headline, design: .serif).weight(.semibold))
                    Text(item.title)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                .layoutPriority(1)
                Spacer()
                RubricStationeryStatusChip(isMapped ? .onTrack : .notStarted, compact: true)
            }
            Text(item.shortDescription)
                .font(.footnote)
                .foregroundStyle(.secondary)
            Text("\(item.learningArea) • \(item.subject) • \(item.yearLevel.isEmpty ? item.band : item.yearLevel)")
                .font(.caption)
                .foregroundStyle(.secondary)
            DisclosureGroup("Provenance") {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Source: \(item.sourceName)")
                    Text("Version: \(item.sourceVersion)")
                    Text("URI: \(item.externalURI)")
                    if !item.licenseName.isEmpty { Text("License: \(item.licenseName)") }
                    if !item.sourceAttribution.isEmpty { Text(item.sourceAttribution) }
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            }
            Button(action: action) {
                Label(isMapped ? "Unmap" : "Map", systemImage: isMapped ? "link.slash" : "link")
                    .frame(minHeight: GradeDraftLayout.minimumTapTarget)
            }
            .buttonStyle(.bordered)
            .accessibilityLabel(isMapped ? "Unmap curriculum reference \(item.code)" : "Map curriculum reference \(item.code)")
        }
        .padding(12)
        .background(Color.white.opacity(0.36), in: RoundedRectangle(cornerRadius: 8, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 8, style: .continuous)
                .stroke(Color(.separator), lineWidth: 0.5)
        )
    }
}
